# Generated by Django 5.1 on 2024-10-06 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='user_id',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='event',
            name='aggregate_id',
            field=models.CharField(max_length=64),
        ),
    ]
