# Generated by Django 5.1 on 2024-11-15 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationSovComBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculation_id', models.CharField(max_length=255)),
                ('is_calculation_positive', models.BooleanField()),
                ('comment', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OffersSovComBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_in_excel_file_sovcom', models.IntegerField(blank=True, null=True, verbose_name='ID в ексель файле')),
                ('actual_sovcom', models.IntegerField(blank=True, null=True, verbose_name='actual столбец')),
                ('rating_sovcom', models.IntegerField(blank=True, null=True, verbose_name='Рейтинг выдачи')),
            ],
        ),
        migrations.CreateModel(
            name='ResponseCalculationSovComBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_id', models.IntegerField()),
                ('dealer_id', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CreditInfoSovComBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('period', models.IntegerField()),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_no_subsidy', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('credit_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_info', to='core.calculationsovcombank')),
            ],
        ),
        migrations.CreateModel(
            name='DealCostSovComBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('currency', models.CharField(max_length=10)),
                ('calculation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal_cost', to='core.calculationsovcombank')),
            ],
        ),
        migrations.CreateModel(
            name='InsuranceSovComBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255)),
                ('period', models.IntegerField()),
                ('agreement_percent', models.DecimalField(decimal_places=3, max_digits=5)),
                ('cost_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('cost_currency', models.CharField(max_length=10)),
                ('payment_type', models.CharField(max_length=255)),
                ('company_type', models.CharField(max_length=255)),
                ('insurer_id', models.CharField(max_length=255)),
                ('calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insurance_list', to='core.calculationsovcombank')),
            ],
        ),
        migrations.AddField(
            model_name='calculationsovcombank',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculations', to='core.responsecalculationsovcombank'),
        ),
    ]
