# Generated by Django 5.1 on 2024-11-25 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_calculationsovcombank_offerssovcombank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecalculationsovcombank',
            name='request_id',
            field=models.CharField(max_length=255),
        ),
    ]
