# Generated by Django 5.1 on 2024-11-25 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_responsecalculationsovcombank_request_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='responsecalculationsovcombank',
            name='dealer_id',
        ),
    ]
