# Generated by Django 5.1 on 2024-11-25 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_responsecalculationsovcombank_dealer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecalculationsovcombank',
            name='dealer_id',
            field=models.CharField(default=12, max_length=255),
            preserve_default=False,
        ),
    ]
