# Generated by Django 5.1 on 2024-11-25 20:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_responsecalculationsovcombank_dealer_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecalculationsovcombank',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
