# Generated by Django 5.1 on 2024-11-25 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_responsecalculationsovcombank_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecalculationsovcombank',
            name='request_id',
            field=models.UUIDField(),
        ),
    ]
