# Generated by Django 5.1 on 2024-11-25 20:58

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_responsecalculationsovcombank_request_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsecalculationsovcombank',
            name='request_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
