# Generated by Django 5.1 on 2024-11-26 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_responsecalculationsovcombank_request_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='calculationsovcombank',
            old_name='calculation_id',
            new_name='calculation_number',
        ),
    ]
