# Generated by Django 5.1 on 2024-11-26 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_rename_calculation_id_calculationsovcombank_calculation_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='responsecalculationsovcombank',
            old_name='request_id',
            new_name='request_id_in_bank',
        ),
    ]
