# Generated by Django 5.1 on 2024-11-26 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_rename_request_id_responsecalculationsovcombank_request_id_in_bank'),
        ('questionnaire', '0021_delete_offerssovcombank_delete_responseapicalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsecalculationsovcombank',
            name='client',
            field=models.ForeignKey(default=51, on_delete=django.db.models.deletion.CASCADE, related_name='calculations_response', to='questionnaire.clientpredata'),
            preserve_default=False,
        ),
    ]
