# Generated by Django 5.0.6 on 2024-07-23 08:05

import credit_v0.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_v0', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarBrand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Марка автомобиля')),
            ],
            options={
                'verbose_name': 'Марка автомобиля',
                'verbose_name_plural': 'Марки автомобилей',
            },
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='brand_car_info',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='condition_car_info',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='eco_class_car_info',
        ),
        migrations.RemoveField(
            model_name='carinfo',
            name='engine_type_car_info',
        ),
        migrations.RemoveField(
            model_name='clientuploaddocument',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientuploaddocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='documentsaleauto',
            name='client',
        ),
        migrations.RemoveField(
            model_name='documentsaleauto',
            name='pts_type_sale_auto',
        ),
        migrations.RemoveField(
            model_name='extrainsurance',
            name='client',
        ),
        migrations.RemoveField(
            model_name='financingconditions',
            name='client',
        ),
        migrations.RemoveField(
            model_name='financingconditions',
            name='financing_term',
        ),
        migrations.CreateModel(
            name='AutoSaleDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pts_number_sale_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ПТС')),
                ('pts_issue_sale_auto', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ПТС')),
                ('pts_issued_by_sale_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан ПТС')),
                ('pts_name_sale_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название ТС по ПТС')),
                ('dcp_number_sale_auto', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер ДКП')),
                ('dcp_issue_date_sale_auto', models.DateField(blank=True, null=True, verbose_name='Дата выдачи ДКП')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='credit_v0.clientpredata')),
                ('pts_type_sale_auto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.typepts', verbose_name='Тип ПТС')),
            ],
            options={
                'verbose_name': 'Документ продажи автомобиля',
                'verbose_name_plural': 'Документы продажи автомобилей',
            },
        ),
        migrations.AlterField(
            model_name='allapplications',
            name='documents',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.autosaledocument'),
        ),
        migrations.CreateModel(
            name='ClientCarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('configuration_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Комплектация')),
                ('year_car_info', models.CharField(blank=True, max_length=4, null=True, verbose_name='Год')),
                ('engine_volume_car_info', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем двигателя')),
                ('power_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Мощность (Л.С.)')),
                ('color_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цвет')),
                ('mileage_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Пробег')),
                ('vin_car_info', models.CharField(blank=True, max_length=17, null=True, verbose_name='VIN')),
                ('car_price_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена автомобиля')),
                ('dealer_equipment_price_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена доп. оборудования от дилера')),
                ('price_date_car_info', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата формирования цены')),
                ('body_number_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер кузова')),
                ('engine_number_car_info', models.CharField(blank=True, max_length=255, null=True, verbose_name='Номер двигателя')),
                ('brand_car_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.carbrand', verbose_name='Марка')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_info', to='credit_v0.clientpredata')),
                ('condition_car_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.carcondition', verbose_name='Состояние')),
                ('eco_class_car_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.ecoclass', verbose_name='Экологический класс')),
                ('engine_type_car_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.enginetype', verbose_name='Тип двигателя')),
            ],
            options={
                'verbose_name': 'Информация о машине',
                'verbose_name_plural': 'Информация о машинах',
            },
        ),
        migrations.AlterField(
            model_name='allapplications',
            name='car_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.clientcarinfo'),
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to=credit_v0.models.upload_to, verbose_name='Выбрать файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.clientpredata')),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.documenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Загруженный документ клиента',
                'verbose_name_plural': 'Загруженные документы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientExtraInsurance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kasko_amount', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='КАСКО')),
                ('kasko_amount_include', models.BooleanField(default=False, verbose_name='Добавить в счет кредита КАСКО')),
                ('gap_amount', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='GAP')),
                ('gap_amount_include', models.BooleanField(default=False, verbose_name='Добавить в счет кредита GAP')),
                ('szh_amount', models.CharField(blank=True, default=0, max_length=255, null=True, verbose_name='Страхование жизни')),
                ('szh_term', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок')),
                ('szh_term_include', models.BooleanField(default=False, verbose_name='Добавить в счет кредита СЖ')),
                ('financial_products_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Финансовые продукты')),
                ('financial_products_amount_include', models.BooleanField(blank=True, max_length=255, null=True, verbose_name='Добавить в счет кредита Фин. продукты')),
                ('installment_commission_include', models.BooleanField(blank=True, default=False, null=True, verbose_name='Снижение процента')),
                ('sms_notification_include', models.BooleanField(blank=True, default=False, null=True, verbose_name='СМС информирование')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_insurance', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Дополнительное страхование',
                'verbose_name_plural': 'Дополнительные страхования',
            },
        ),
        migrations.AlterField(
            model_name='allapplications',
            name='extra_insurance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.clientextrainsurance'),
        ),
        migrations.CreateModel(
            name='ClientFinancingCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первоначальный взнос')),
                ('monthly_payment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ежемесячный платеж')),
                ('deferred_payment', models.BooleanField(default=False, verbose_name='Отложенный платеж')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financing_conditions', to='credit_v0.clientpredata')),
                ('financing_term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.financingterm', verbose_name='Срок финансирования')),
            ],
            options={
                'verbose_name': 'Условия финансирования',
                'verbose_name_plural': 'Условия финансирования',
            },
        ),
        migrations.AlterField(
            model_name='allapplications',
            name='financing_conditions',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.clientfinancingcondition'),
        ),
        migrations.DeleteModel(
            name='CarMake',
        ),
        migrations.DeleteModel(
            name='ClientUploadDocument',
        ),
        migrations.DeleteModel(
            name='DocumentSaleAuto',
        ),
        migrations.DeleteModel(
            name='CarInfo',
        ),
        migrations.DeleteModel(
            name='ExtraInsurance',
        ),
        migrations.DeleteModel(
            name='FinancingConditions',
        ),
    ]
