# Generated by Django 5.0.6 on 2024-07-23 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_v0', '0002_carbrand_remove_carinfo_brand_car_info_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField()),
                ('title_offer', models.CharField(max_length=255)),
                ('name_bank_offer', models.CharField(max_length=255)),
                ('term_offer', models.IntegerField()),
                ('stavka_offer', models.CharField(max_length=255)),
                ('pay_offer', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Предложение клиента',
                'verbose_name_plural': 'Предложения клиентов',
            },
        ),
        migrations.DeleteModel(
            name='OffersClient',
        ),
    ]
