# Generated by Django 5.0.6 on 2024-07-23 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_v0', '0003_clientoffer_delete_offersclient'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientinfopersonal',
            name='client',
        ),
        migrations.RemoveField(
            model_name='clientinfopersonal',
            name='gender_choice_client',
        ),
        migrations.RemoveField(
            model_name='clientinfopersonal',
            name='housing_type_client',
        ),
        migrations.RemoveField(
            model_name='clientinfopersonal',
            name='social_status_client',
        ),
        migrations.RemoveField(
            model_name='contactclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='contactclient',
            name='housing_type_contact',
        ),
        migrations.RemoveField(
            model_name='contactclient',
            name='phone_type_contact',
        ),
        migrations.RemoveField(
            model_name='driverlicense',
            name='client',
        ),
        migrations.RemoveField(
            model_name='education',
            name='client',
        ),
        migrations.RemoveField(
            model_name='education',
            name='education_level_client',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='activity_code',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='client',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='organization_type',
        ),
        migrations.RemoveField(
            model_name='employment',
            name='position_type',
        ),
        migrations.RemoveField(
            model_name='expenses',
            name='client',
        ),
        migrations.RemoveField(
            model_name='familyinfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='familyinfo',
            name='marital_status',
        ),
        migrations.RemoveField(
            model_name='financialinfo',
            name='client',
        ),
        migrations.RemoveField(
            model_name='internationalpassport',
            name='client',
        ),
        migrations.RemoveField(
            model_name='passportclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='pensioncertificate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='client',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='purchase_method_real_estate',
        ),
        migrations.RemoveField(
            model_name='realestate',
            name='real_estate_type',
        ),
        migrations.RemoveField(
            model_name='selectoffersclient',
            name='client',
        ),
        migrations.RemoveField(
            model_name='taxdocument',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='client',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='purchase_method_vehicle',
        ),
        migrations.CreateModel(
            name='ClientCitizenship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('russian_citizenship', models.BooleanField(blank=True, default=False, null=True, verbose_name='Гражданство Россия, единственно')),
                ('residence_permit', models.BooleanField(blank=True, default=False, null=True, verbose_name='Вид на жительство в другой стране')),
                ('us_citizenship', models.BooleanField(blank=True, default=False, null=True, verbose_name='Гражданство США')),
                ('birth_place_citizenship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения')),
                ('tax_resident_foreign', models.BooleanField(blank=True, default=False, null=True, verbose_name='Налоговый резидент иностранного государства')),
                ('tax_residence_countries', models.CharField(blank=True, max_length=255, null=True, verbose_name='Страны налогового резиденства')),
                ('foreign_inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН иностранного государства')),
                ('birth_country_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.country', verbose_name='Страна рождения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizenship', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Гражданство клиента',
                'verbose_name_plural': 'Гражданства клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('living_address_contact', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес проживания')),
                ('living_start_date_contact', models.DateField(blank=True, null=True, verbose_name='Дата начала проживания')),
                ('phone_number_contact', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('email_contact', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('notes_contact', models.TextField(blank=True, null=True, verbose_name='Примечание')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_data', to='credit_v0.clientpredata')),
                ('housing_type_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.housingtype', verbose_name='Тип жилья')),
                ('phone_type_contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='credit_v0.phonetype', verbose_name='Тип телефона')),
            ],
            options={
                'verbose_name': 'Контактные данные клиента',
                'verbose_name_plural': 'Контактные данные клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientDriverLicense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number_driver_license', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер')),
                ('issue_date_driver_license', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issued_by_driver_license', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кем выдан')),
                ('experience_start_date_driver_license', models.DateField(blank=True, null=True, verbose_name='Стаж (дата выдачи первого ВУ)')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_license_data', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Водительское удостоверение клиента',
                'verbose_name_plural': 'Водительские удостоверения клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education', to='credit_v0.clientpredata')),
                ('education_level_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.educationlevel', verbose_name='Уровень образования')),
            ],
            options={
                'verbose_name': 'Образование клиента',
                'verbose_name_plural': 'Образование клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientEmployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_inn', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН организации')),
                ('organization_form', models.CharField(blank=True, max_length=255, null=True, verbose_name='Форма организации (чем занимается)')),
                ('organization_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Юр. название')),
                ('position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Наименование должности')),
                ('registration_address_employment', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес регистрации')),
                ('phone_number_organization', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер телефона')),
                ('current_experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж на текущем месте')),
                ('total_experience', models.CharField(blank=True, max_length=255, null=True, verbose_name='Стаж общий')),
                ('shift_method', models.BooleanField(blank=True, default=False, null=True, verbose_name='Работа вахтовым методом')),
                ('official_position', models.BooleanField(blank=True, default=False, null=True, verbose_name='Должностное лицо')),
                ('activity_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.activitycode', verbose_name='Код вида деятельности')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment', to='credit_v0.clientpredata')),
                ('organization_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.organizationtype', verbose_name='Тип организации')),
                ('position_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.positiontype', verbose_name='Тип должности')),
            ],
            options={
                'verbose_name': 'Трудоустройство клиента',
                'verbose_name_plural': 'Трудоустройство клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientExpenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mandatory_payments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Обязательные платежи в месяц')),
                ('loan_payments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Платежи по кредитам')),
                ('mortgage_payments', models.CharField(blank=True, max_length=255, null=True, verbose_name='Платежи по ипотеке')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Расходы клиента',
                'verbose_name_plural': 'Расходы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientFamilyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children_under_18', models.IntegerField(blank=True, null=True, verbose_name='Дети до 18 лет')),
                ('dependents', models.IntegerField(blank=True, null=True, verbose_name='Иждивенцы')),
                ('years_married', models.IntegerField(blank=True, null=True, verbose_name='Количество лет в браке')),
                ('official_position_relative', models.BooleanField(default=False, verbose_name='Должностное лицо (родственник)')),
                ('degree_of_kinship', models.CharField(blank=True, max_length=255, null=True, verbose_name='Степень родства')),
                ('relative_position', models.CharField(blank=True, max_length=255, null=True, verbose_name='Должность и место работы')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_info', to='credit_v0.clientpredata')),
                ('marital_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.maritalstatus', verbose_name='Семейное положение')),
            ],
            options={
                'verbose_name': 'Семейная информация клиента',
                'verbose_name_plural': 'Семейная информация клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма дохода')),
                ('confirmed_income_amount', models.CharField(blank=True, max_length=255, null=True, verbose_name='Подтвержденная сумма')),
                ('income_proof_document', models.CharField(blank=True, max_length=255, null=True, verbose_name='Документ подтверждающий доход')),
                ('income_source', models.CharField(blank=True, max_length=255, null=True, verbose_name='Источник доходов')),
                ('disposable_income', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма которую вы можете выделять')),
                ('spouse_income', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма доходов супруга')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Финансовая информация клиента',
                'verbose_name_plural': 'Финансовая информация клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientInternationalPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number_international_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер')),
                ('issue_date_international_passport', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('issued_by_international_passport', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кем выдан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='international_passport', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Загранпаспорт клиента',
                'verbose_name_plural': 'Загранпаспорта клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientPassport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number_passport', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер')),
                ('issue_date_passport', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('division_code_passport', models.CharField(blank=True, max_length=10, null=True, verbose_name='Код подразделения')),
                ('issued_by_passport', models.CharField(blank=True, max_length=200, null=True, verbose_name='Кем выдан')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_data', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Паспортные данные клиента',
                'verbose_name_plural': 'Паспортные данные клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientPensionCertificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_pension_sert', models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pension_certificate', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Пенсионное свидетельство клиента',
                'verbose_name_plural': 'Пенсионные свидетельства клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientPersonalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_to_contact_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Обращение')),
                ('first_name_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Имя')),
                ('last_name_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Фамилия')),
                ('middle_name_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Отчество')),
                ('type_client', models.CharField(blank=True, default='Физическое лицо', max_length=255, null=True, verbose_name='Тип')),
                ('product_client', models.CharField(blank=True, default='Кредит', max_length=255, null=True, verbose_name='Продукт')),
                ('birth_date_client', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('registration_address_client', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес регистрации')),
                ('registration_date_client', models.DateField(blank=True, null=True, verbose_name='Дата регистрации')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_person_data', to='credit_v0.clientpredata')),
                ('gender_choice_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.gender', verbose_name='Пол')),
                ('housing_type_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.housingtype', verbose_name='Тип жилья')),
                ('social_status_client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.socialstatus', verbose_name='Социальный статус')),
            ],
            options={
                'verbose_name': 'Личная информация клиента',
                'verbose_name_plural': 'Личная информация клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientRealEstate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_real_estate', models.CharField(blank=True, max_length=255, null=True, verbose_name='Адрес')),
                ('matches_registration_address_real_estate', models.BooleanField(default=False, verbose_name='Совпадает с местом регистрации')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='real_estate', to='credit_v0.clientpredata')),
                ('purchase_method_real_estate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.purchasemethod', verbose_name='Способ приобретения')),
                ('real_estate_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.realestatetype', verbose_name='Тип недвижимости')),
            ],
            options={
                'verbose_name': 'Недвижимость клиента',
                'verbose_name_plural': 'Недвижимость клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientTaxDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_number_tax_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='Серия и номер')),
                ('number_tax_document', models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_document', to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Налоговый документ клиента',
                'verbose_name_plural': 'Налоговые документы клиентов',
            },
        ),
        migrations.CreateModel(
            name='ClientVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_vehicle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Марка')),
                ('year_vehicle', models.IntegerField(blank=True, null=True, verbose_name='Год')),
                ('model_vehicle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Модель')),
                ('purchase_year', models.IntegerField(blank=True, null=True, verbose_name='Год приобретения')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='credit_v0.clientpredata')),
                ('purchase_method_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='credit_v0.purchasemethod', verbose_name='Способ приобретения')),
            ],
            options={
                'verbose_name': 'Транспортное средство клиента',
                'verbose_name_plural': 'Транспортные средства клиентов',
            },
        ),
        migrations.CreateModel(
            name='SelectedClientOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(blank=True, null=True)),
                ('total_loan_amount_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Сумма кредита')),
                ('car_price_display_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Цена автомобиля')),
                ('initial_payment_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Первоначальный взнос')),
                ('term_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Срок кредита')),
                ('title_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название предложения')),
                ('monthly_payment_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ежемесячный платеж')),
                ('stavka_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ставка')),
                ('name_bank_select', models.CharField(blank=True, max_length=255, null=True, verbose_name='Название банка')),
                ('status_select_offer', models.CharField(blank=True, max_length=255, null=True)),
                ('info_from_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('id_app_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('id_app_in_system', models.IntegerField(blank=True, default=0, null=True)),
                ('link_to_detail_from_bank', models.CharField(blank=True, max_length=255, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='credit_v0.clientpredata')),
            ],
            options={
                'verbose_name': 'Выбранное предложение клиента',
                'verbose_name_plural': 'Выбранные предложения клиентов',
            },
        ),
        migrations.DeleteModel(
            name='Citizenship',
        ),
        migrations.DeleteModel(
            name='ClientInfoPersonal',
        ),
        migrations.DeleteModel(
            name='ContactClient',
        ),
        migrations.DeleteModel(
            name='DriverLicense',
        ),
        migrations.DeleteModel(
            name='Education',
        ),
        migrations.DeleteModel(
            name='Employment',
        ),
        migrations.DeleteModel(
            name='Expenses',
        ),
        migrations.DeleteModel(
            name='FamilyInfo',
        ),
        migrations.DeleteModel(
            name='FinancialInfo',
        ),
        migrations.DeleteModel(
            name='InternationalPassport',
        ),
        migrations.DeleteModel(
            name='PassportClient',
        ),
        migrations.DeleteModel(
            name='PensionCertificate',
        ),
        migrations.DeleteModel(
            name='RealEstate',
        ),
        migrations.DeleteModel(
            name='SelectOffersClient',
        ),
        migrations.DeleteModel(
            name='TaxDocument',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
