# Generated by Django 5.1 on 2024-08-22 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_v0', '0004_remove_clientinfopersonal_client_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dealership',
            name='is_active',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='active_dealership',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='credit_v0.dealership'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='dealership_manager',
            field=models.ManyToManyField(blank=True, related_name='managed_profiles', to='credit_v0.dealership', verbose_name='Дилерский центр'),
        ),
    ]
