# Generated by Django 5.1 on 2024-09-03 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('credit_v0', '0006_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='A',
        ),
    ]
