# Generated by Django 5.1 on 2024-09-16 18:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dealership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название дилерского центра')),
                ('organisation_name', models.CharField(max_length=255, verbose_name='Название организации')),
            ],
            options={
                'verbose_name': 'Дилерский центр',
                'verbose_name_plural': 'Дилерские центры',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_manager', models.CharField(max_length=30, null=True, verbose_name='Имя')),
                ('last_name_manager', models.CharField(max_length=30, null=True, verbose_name='Фамилия')),
                ('middle_name_manager', models.CharField(max_length=30, null=True, verbose_name='Отчество')),
                ('organization_manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Организация')),
                ('role_manager', models.CharField(max_length=50, verbose_name='Роль')),
                ('date_of_birth_manager', models.DateField(blank=True, null=True, verbose_name='Дата рождения')),
                ('phone_number_manager', models.CharField(blank=True, max_length=20, null=True, verbose_name='Телефонный номер')),
                ('status_manager', models.BooleanField(default=True, verbose_name='Статус')),
                ('passport_series_manager', models.CharField(blank=True, max_length=10, null=True, verbose_name='Серия паспорта')),
                ('passport_number_manager', models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер паспорта')),
                ('division_code_manager', models.CharField(blank=True, max_length=7, null=True, verbose_name='Код подразделения')),
                ('issued_by_manager', models.CharField(blank=True, max_length=255, null=True, verbose_name='Кем выдан')),
                ('issue_date_manager', models.DateField(blank=True, null=True, verbose_name='Дата выдачи')),
                ('active_dealership', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_profiles', to='users.dealership')),
                ('dealership_manager', models.ManyToManyField(blank=True, related_name='managed_profiles', to='users.dealership', verbose_name='Дилерский центр')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профили',
            },
        ),
    ]
