# Generated by Django 5.1 on 2024-09-17 09:45

import apps.users.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, unique=True, verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Тип документа пользователя',
                'verbose_name_plural': 'Типы документов пользователей',
            },
        ),
        migrations.CreateModel(
            name='UserDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to=apps.users.models.user_upload_to, verbose_name='Выбрать файл')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userdocumenttype', verbose_name='Тип документа')),
            ],
            options={
                'verbose_name': 'Загруженный документ пользователя',
                'verbose_name_plural': 'Загруженные документы пользователей',
            },
        ),
    ]
