# Generated by Django 5.1 on 2024-10-04 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdocument',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userdocumenttype', verbose_name='Тип документа'),
        ),
    ]
