# Generated by Django 5.1 on 2024-09-16 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='active_dealership',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dealership_manager',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Dealership',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
