# Generated by Django 5.1 on 2024-09-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_remove_userprofile_active_dealership_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserDocumentType',
        ),
    ]
