# Generated by Django 5.1 on 2024-10-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0003_delete_userdocumenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedclientoffer',
            name='status_selected_card',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
