# Generated by Django 5.1 on 2024-10-10 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0004_selectedclientoffer_status_selected_card'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='selectedclientoffer',
            name='status_selected_card',
        ),
    ]
