# Generated by Django 5.1 on 2024-10-13 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0005_remove_selectedclientoffer_status_selected_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncomeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=255, unique=True, verbose_name='Тип дохода')),
            ],
            options={
                'verbose_name': 'Тип дохода',
                'verbose_name_plural': 'Типы доходов',
            },
        ),
        migrations.AddField(
            model_name='clientpredata',
            name='country_name_pre_client',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='clientfinancialinfo',
            name='income_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='questionnaire.incometype', verbose_name='Тип дохода'),
        ),
    ]
