# Generated by Django 5.1 on 2024-10-13 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0006_incometype_clientpredata_country_name_pre_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpredata',
            name='country_name_pre_client',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Страна регистрации'),
        ),
    ]
