# Generated by Django 5.1 on 2024-10-13 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0008_remove_clientpredata_country_name_pre_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpersonalinfo',
            name='post_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Почтовый индекс'),
        ),
    ]
