# Generated by Django 5.1 on 2024-10-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0009_clientpersonalinfo_post_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpredata',
            name='product_pre_client',
            field=models.CharField(blank=True, default='Кредит', max_length=255, null=True, verbose_name='Продукт'),
        ),
    ]
