# Generated by Django 5.1 on 2024-10-14 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0012_alter_clientpersonalinfo_product_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientpersonalinfo',
            name='fact_address_same_registration',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Место проживания совпадает с местом регистрации'),
        ),
    ]
