# Generated by Django 5.1 on 2024-10-14 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0013_clientpersonalinfo_fact_address_same_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientpersonalinfo',
            name='fact_address_same_registration',
            field=models.BooleanField(default=False, verbose_name='Место проживания совпадает с местом регистрации'),
        ),
    ]
