# Generated by Django 5.1 on 2024-10-14 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0014_alter_clientpersonalinfo_fact_address_same_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcitizenship',
            name='birth_place_citizenship',
        ),
        migrations.AddField(
            model_name='clientpersonalinfo',
            name='birth_place_citizenship',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Место рождения'),
        ),
    ]
