# Generated by Django 5.1 on 2024-10-14 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0015_remove_clientcitizenship_birth_place_citizenship_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientrealestate',
            name='matches_registration_address_real_estate',
        ),
    ]
