# Generated by Django 5.1 on 2024-10-17 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0016_remove_clientrealestate_matches_registration_address_real_estate'),
    ]

    operations = [
        migrations.AddField(
            model_name='selectedclientoffer',
            name='request_id_in_bank',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
