# Generated by Django 5.1 on 2024-10-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0017_selectedclientoffer_request_id_in_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selectedclientoffer',
            name='status_select_offer',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Статус заявки в банке'),
        ),
    ]
