# Generated by Django 5.1 on 2024-11-14 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0019_offerssovcombank_responseapicalculator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responseapicalculator',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='response_api_calculator', to='questionnaire.clientpredata'),
        ),
    ]
