# Generated by Django 5.1 on 2024-11-15 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0020_alter_responseapicalculator_client'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OffersSovComBank',
        ),
        migrations.DeleteModel(
            name='ResponseAPICalculator',
        ),
    ]
