name: Run Tests

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || true
        pip install python-dotenv
#        pip install pytest-playwright
#
#    - name: Install Playwright browsers 7
#      run: |
#        npm install @playwright/test
#        npx playwright install
#        playwright install

    - name: Create .env file from secret
      run: echo "${{ secrets.ENV }}" > .env

    - name: Create settings.py file from secret
      run: |
        echo "${{ secrets.SETTINGS }}" > app_v0/settings.py
#        echo "${{ secrets.SETTINGS }}" | base64 --decode > app_v0/settings.py
        cat app_v0/settings.py
    - name: Run  tests
      run: pytest

#    - name: Run Playwright tests
#      run: pytest -s credit_v0/tests/playwright/test_pw.py
